apiVersion: apps/v1
kind: Deployment
metadata:
  name: hummus
  namespace: hummus
  labels:
    app.kubernetes.io/name: hummus
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hummus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hummus
    spec:
      containers:
      - name: hummus
        image: hummus:latest
        imagePullPolicy: Never # as long as im using local images...
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3        
        livenessProbe:
          httpGet:
            path: /api/ready
            port: 8080
          periodSeconds: 5 
        envFrom:
        - configMapRef:
            name: hummus
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: hummus
              key: mongodb-uri
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: hummus
              key:  sendgrid-api-key
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: hummus
              key:  aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: hummus
              key:  aws-secret-access-key
        - name: RECAPTCHA_KEY
          valueFrom:
            secretKeyRef:
              name: hummus
              key:  recaptcha-key
        - name: RECAPTCHA_SECRET
          valueFrom:
            secretKeyRef:
              name: hummus
              key:  recaptcha-secret
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: hummus
              key:  jwt-key
        #resources:
        #  limits:
        #    cpu: "1"
        #    memory: "1Gi"
        #  requests:
        #    cpu: "0.5"
        #    memory: "500Mi"
        ports:
        - containerPort: 8080
