apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hummus.fullname" . }}
  labels:
    {{- include "hummus.labels" . | nindent 4 }}
data:
  ADMIN_EMAIL: {{ .Values.adminEmail | quote }}
  JOIN_EMAIL: {{ .Values.joinEmail | quote }}
  SUPPORT_EMAIL: {{ .Values.supportEmail | quote }} 
  EMAIL_SERVICE_URL: {{ .Values.emailServiceUrl | quote }}
