apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hummus.fullname" . }}
  labels:
    {{- include "hummus.labels" . | nindent 4 }}
data:
  ADMIN_EMAIL: {{ .Values.adminEmail | quote }}
  JOIN_EMAIL: {{ .Values.joinEmail | quote }}
  SUPPORT_EMAIL: {{ .Values.supportEmail | quote }} 
  EMAIL_SERVICE_URL: {{ .Values.emailServiceUrl | quote }}
  {{- if .Values.noRecaptcha }}
  NO_RECAPTCHA: {{ .Values.noRecaptcha | quote }}
  {{- end}}
  {{- if .Values.tokenServiceDomains }}
  TOKEN_SERVICE_DOMAINS: {{ .Values.tokenServiceDomains | quote }}
  {{- end}}
  {{- if .Values.awsRegion }}
  AWS_REGION: {{ .Values.awsRegion | quote }}
  {{- end}}
  {{- if .Values.awsBucket }}
  AWS_BUCKET: {{ .Values.awsBucket | quote }}
  {{- end}}
