apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hummus.fullname" . }}
  labels:
    {{- include "hummus.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ .Values.mongodbUri | b64enc }}
  sendgrid-api-key: {{ .Values.sendgridApiKey | b64enc }}
  aws-access-key-id: {{ .Values.awsAccessKeyId | b64enc }}
  aws-secret-access-key: {{ .Values.awsSecretAccessKey | b64enc }}
  recaptcha-key: {{ .Values.recaptchaKey | b64enc }}
  recaptcha-secret: {{ .Values.recaptchaSecret | b64enc }}
  jwt-key: {{ .Values.jwtKey | b64enc }}