apiVersion: v2
name: hummus
description: A Helm chart for Kubernetes
type: application
# chart version
version: 0.1.10
# hummus app version
appVersion: "0.1.5"
dependencies:
- name: prometheus
  version: "15.10.5"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: metrics.enabled
- name: grafana
  version: "6.32.7"
  repository: "https://grafana.github.io/helm-charts"
  condition: metrics.enabled
- name: elasticsearch
  version: "7.17.3"
  repository: "https://helm.elastic.co"
  condition: logging.enabled
- name: kibana
  version: "7.17.3"
  repository: "https://helm.elastic.co"
  condition: logging.enabled
- name: fluentd
  version: "0.3.9"
  repository: "https://fluent.github.io/helm-charts"
  condition: logging.enabled
