apiVersion: v2
name: hummus
description: A Helm chart for Kubernetes
type: application
# chart version
version: 0.1.6
# hummus app version
appVersion: "0.1.3"
dependencies:
- name: prometheus
  version: "15.10.5"
  repository: "https://prometheus-community.github.io/helm-charts"